[project]
name = "dragonfly-mainframe"
version = "0.1.0"
description = "Distributes tasks to dragonfly-clients and handles package status updates."
authors = [
    {name = "jz9", email = "69145546+jonathan-d-zhang@users.noreply.github.com"},
]
requires-python = ">=3.10"
license = {text = "MIT"}

dependencies = [
    "fastapi>=0.95.1",
    "uvicorn[standard]>=0.22.0",
]

[tool.pdm]

[tool.pdm.dev-dependencies]
lint = [
    "pre-commit>=3.3.1",
    "ruff>=0.0.265",
    "black>=23.3.0",
    "isort>=5.12.0",
]

[tool.isort]
profile = "black"

[tool.black]
target-version = ["py310"]
line-length = 120

[tool.ruff]
line-length = 120
